tdd_spec_capybara_cucumber/i-rock/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  resources :achievements
end

tdd_spec_capybara_cucumber/i-rock/app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :user, presence: true
  validates :title, uniqueness: {
    scope: :user_id,
    message: "you can't have two achievements with the same title"
  }
  #validate :unique_title_for_one_user

  enum privacy: [:public_access, :private_access, :friends_access ]

  def description_html
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
  end

  def silly_title
    "#{title} by #{user.email}"
  end

  def self.by_letter(letter)
    includes(:user).where("title LIKE ?", "#{letter}%").order("users.email")
  end
end

tdd_spec_capybara_cucumber/i-rock/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

tdd_spec_capybara_cucumber/i-rock/app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action  :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
  before_action :owners_only, only: [:edit, :update, :destroy]

  def index
    @achievements = Achievement.public_access
  end

  def new
    @achievement = Achievement.new
  end

  def create
    @achievement = Achievement.new(achievement_params)
    if @achievement.save
      redirect_to achievement_path(@achievement), notice: 'Achievement has been created'
    else
      render :new 
    end
  end

  def edit
  end

  def update
    if @achievement.update_attributes(achievement_params)
      redirect_to achievement_path(@achievement)
    else
      render :edit
    end
  end

  def show
    @achievement = Achievement.find(params[:id])
  end

  def destroy
    @achievement.destroy
    redirect_to achievements_path
  end
  private

  def achievement_params
    params.require(:achievement).permit(:title, :description, :privacy, :cover_image, :featured)
    
  end

  def owners_only
    @achievement = Achievement.find(params[:id])
    if current_user != @achievement.user
      redirect_to achievements_path
    end
  end
end

tdd_spec_capybara_cucumber/i-rock/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tdd_spec_capybara_cucumber/i-rock/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

tdd_spec_capybara_cucumber/i-rock/app/helpers/application_helper.rb
module ApplicationHelper
end

tdd_spec_capybara_cucumber/i-rock/app/views/achievements/new.html.erb
<%= simple_form_for @achievement do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :privacy, collection: Hash[Achievement.privacies.map { |k,v| [ k.split('_').first.capitalize, k ]}] %>
  <%= f.input :featured, label: "Featured achievement" %>
  <%= f.input :cover_image, as: :file %>
  <%= f.submit 'Create Achievement', class: 'btn btn-primary' %>
<% end %>

tdd_spec_capybara_cucumber/i-rock/app/views/achievements/show.html.erb
<h1><%= @achievement.title %></h1>
<div>
  <%= @achievement.description_html.html_safe %>
</div>

tdd_spec_capybara_cucumber/i-rock/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I Rock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">I Rock</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'New Achievement', new_achievement_path %></li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

      <% if flash[:notice] %>
         <div class="alert alert-info"> 
           <%= flash[:notice] %>
         </div>
      <% end %> 
      <% if flash[:alert] %>
         <div class="alert alert-info"> 
           <%= flash[:alert] %>
         </div>
      <% end %> 

    <%= yield %>
  </div>

</body>
</html>

tdd_spec_capybara_cucumber/i-rock/app/views/welcome/index.html.erb
<h1>Welcome</h1>