ruby_on_rails_4_getting_started/HU/config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  root 'home#index'
  
  get '/about' => 'home#about'
 
  get 'questions/:id' => 'home#question'
  post '/questions' => 'home#temp'

  post '/answers' => 'home#temp'

end

ruby_on_rails_4_getting_started/HU/app/models/answer.rb
class Answer < ActiveRecord::Base

  include HasGravatar
  
  belongs_to :question

end

ruby_on_rails_4_getting_started/HU/app/models/concerns/has_gravatar.rb
module HasGravatar

  def gravatar
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
  end

end

ruby_on_rails_4_getting_started/HU/app/models/question.rb
class Question < ActiveRecord::Base

  include HasGravatar

  has_many :answers

end

ruby_on_rails_4_getting_started/HU/app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    question = Question.find(params[:answer][:question_id])
    answer =  question.answers.create(answer_params)
    
    MainMailer.notify_question_author(answer).deliver_later

    session[:current_user_email] = answer_params[:email]
    redirect_to question
  end

  private

  def answer_params
    params.require(:answer).permit(:email, :body)
  end

end

ruby_on_rails_4_getting_started/HU/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).all
  end

  def about
  end

  def temp
    redirect_to root_path
  end

  def question
  end
end

ruby_on_rails_4_getting_started/HU/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
 
  def create
    Question.create(questions_params)
    session[:current_user_email] = questions_params[:email]
    redirect_to root_path
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(created_at: :desc)
  end 

  private

  def questions_params
    params.require(:question).permit(:email, :body)
  end

end

ruby_on_rails_4_getting_started/HU/app/helpers/answers_helper.rb
module AnswersHelper
end

ruby_on_rails_4_getting_started/HU/app/helpers/application_helper.rb
module ApplicationHelper

  def current_user_email
    session[:current_user_email]
  end

end

ruby_on_rails_4_getting_started/HU/app/helpers/home_helper.rb
module HomeHelper
end

ruby_on_rails_4_getting_started/HU/app/helpers/questions_helper.rb
module QuestionsHelper
end

ruby_on_rails_4_getting_started/HU/app/views/home/_navbar.html.erb
	<nav class= "navbar navbar-inverse">
	  <div class="container-fluid">
		  <div class="navbar-header">
			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				  <span class="sr-only">Toggle navigation</span>
				  <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
          <span class="icon-bar"></span>
				</button>
        <a class="navbar-brand" href="<%= root_path %>">History of the Universe</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
          <li class="navbar-text"><%= current_user_email %></li>
					<li><form><a href="#" class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#new-question-modal">Ask Question</a></form></li>
				</ul>
			</div>
		</div>
	</nav>

ruby_on_rails_4_getting_started/HU/app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Answer</h4>
      </div>
      <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>
        <input type="hidden" name="answer[question_id]" value="<%= @question.id %>" />
        <div class="modal-body">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="answer[email]" class="form-control" id="inputEmail" placeholder="Email" value="<%= current_user_email %>" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputAnswer" class="col-sm-2 control-label">Answer</label>
            <div class="col-sm-10">
              <textarea class="form-control" name="answer[body]" id="inputAnswer" placeholder="What is your answer?" required></textarea>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

ruby_on_rails_4_getting_started/HU/app/views/home/_new_question_form.html.erb
    <div class="modal fade" id="new-question-modal" tabindex="-1">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times;</span></button>
            <h4 class="modal-title">New Question</h4>
          </div>
          <%= form_for :question, url: '/questions', html: {class: 'form-horizontal'} do %>
            <div class="modal-body">
              <div class="form-group">
                <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                  <input type="email" name="question[email]" class="form-control" id="inputEmail" placeholder="Email" value="<%= current_user_email %>" required>
                </div>
              </div>
              <div class="form-group">
                <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
                <div class="col-sm-10">
                  <textarea class="form-control" id="inputQuestion" name="question[body]" placeholder="What would you like to know" required></textarea>
                </div>
              </div>
            </div>  
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="Submit" class="btn btn-primary">Submit</button>
            </div>
          <% end %>
        </div>
      </div>
    </div

ruby_on_rails_4_getting_started/HU/app/views/home/about.html.erb
<h1>About us</h1>

ruby_on_rails_4_getting_started/HU/app/views/home/index.html.erb
<div class="well">
	<h4>The Universe is the totality of everything that exists, has existed, or ever will exist.</h4>
	<p>This Q&amp;A site is dedicated to questions about the history of the Universe</p>
</div>

  
<div class="container">
  <div class="question-boxes">
    <% @questions.each do |q| %>
      <div class="media" data-target="<%= question_path(q) %>">
        <div class="media-left">
          <a href="#">
            <img class="media-object" src="<%= q.gravatar %>">
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= q.email %> asked:</h4>
          <div class="time hidden-xs">
            <%= time_ago_in_words q.created_at %> ago
          </div>
          <%= truncate q.body, length: 300 %>
          <div class="answer_button hidden-xs">
            <a href="<%= question_path(q) %>" class="btn btn-success btn-xs">View Answers</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if @questions.empty? %>
    <div class="alert alert-info">
      Nothing here yet, be the first to ask.
    </div>
  <% end %>
</div>

ruby_on_rails_4_getting_started/HU/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>History of the Universe</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'home/navbar' %>

  <%= yield %>

  <%= render 'home/new_question_form' %>

</body>
</html>

ruby_on_rails_4_getting_started/HU/app/views/questions/show.html.erb
<div class="container">
  <div class="lead well">
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object" src="<%= @question.gravatar %>">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= @question.email %> asked:</h4>
        <%= @question.body %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

      <div>
         <button type=button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</button>
      </div>

      <%= render 'home/new_answer_form' %>

      <% @answers.each do |answer| %>
        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="<%= answer.gravatar %>">
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= answer.email %> asked:</h4>
            <div>
              <%= time_ago_in_words answer.created_at %> ago
            </div>
            <%= answer.body %>
          </div>
        </div>
      <% end %>

      <% if @answers.empty? %>
        <div class="alert alert-info">
          Nothing here yet, be the first to answer this question. 
        </div>
      <% end %>
    </div>
  </div>
</div>